apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-client-application
spec:
  destination:
    namespace: app-client
    server: https://kubernetes.default.svc
  project: default
  source:
    path: <GitHub_Manifest_Repo_Path>
    repoURL: <Your_GitHub_Repository_URL>
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
